### ISSUE TITLE
是否有后续对于开发者的贡献指南？

### ISSUE THREAD

**Issue by Misaka-L** [Tualin14/baPlayer#1]
### 如在 README 中标记使用的 Unity 编辑器版本和须知避免以下尴尬情况
![image](https://user-images.githubusercontent.com/42287372/204122276-c8a5f615-376e-4ca9-8096-b2afe5024013.png)
![image](https://user-images.githubusercontent.com/42287372/204122582-3312a505-56a0-4599-8df6-026123a9128c.png)

**Comment by Tualin14** [comment]
会的，这次更新重构代码模块化就是为了这个。
目前还没写这些，选择的unity版本和游戏同版本。
刚提交完最后一部分，现在才开始写文档。

**Comment by Misaka-L** [comment]
> 会的，这次更新重构代码模块化就是为了这个。
> 
> 目前还没写这些，选择的unity版本和游戏同版本。
> 
> 刚提交完最后一部分，现在才开始写文档。

感谢回复，辛苦了
