### ISSUE TITLE
unity專案有class缺失

### ISSUE THREAD

**Issue by chris312319** [Tualin14/baPlayer#10]
開啟unity專案後報錯
SkeletonBinary和SkeletonJson缺失
尚不確定是否有其他也缺失了
請問是特意移除的嬤

**Comment by Tualin14** [comment]
这俩个项目里有吧

因为这俩后续有改动但不方便上传就忽略了。
所以后续更改不上传到库里（对运行无影响）
但未改动在库里。

**Comment by Tualin14** [comment]
那俩在

[这里](https://github.com/Tualin14/ArisStudio/commit/9f95c22afbf9c5b9dce19852a95c46575f479e29)

看来是修改这俩文件时给忽略了

**Comment by chris312319** [comment]
> 那俩在
> 
> [这里](https://github.com/Tualin14/ArisStudio/commit/9f95c22afbf9c5b9dce19852a95c46575f479e29)
> 
> 看来是修改这俩文件时给忽略了

感謝大佬!因為也想做個編輯器 想參考大老的做法

**Comment by kiraio-moe** [comment]
> 開啟unity專案後報錯 SkeletonBinary和SkeletonJson缺失 尚不確定是否有其他也缺失了 請問是特意移除的嬤

To fix this, delete `Spine` folder then download spine-unity 3.8 (https://esotericsoftware.com/files/runtimes/unity/spine-unity-3.8-2021-11-10.unitypackage) and import it again. **Don't overwrite existing assets**.

Why 3.8? Cause when I try to use the latest version, there will be a `NullReferenceException` if there are operations related to the Skeleton which doesn't know where it's coming from even if you debug it. Also the Spine 2D asset/Spr/Live 2D that @Tualin14 provided is produced in Spine Editor v3.8.76.

It's a compatibility issue (https://github.com/EsotericSoftware/spine-runtimes/tree/4.1/spine-unity#spine-version)
> spine-unity (4.1) works with data exported from Spine 4.1.xx.

So, if the source is based on v3.8.x, you also need spine-unity 3.8 and so on.

Hope this help :)

Edit:
> 感謝大佬!因為也想做個編輯器 想參考大老的做法

Oh, looks like you fixed this.

**Comment by chris312319** [comment]
> > 開啟unity專案後報錯 SkeletonBinary和SkeletonJson缺失 尚不確定是否有其他也缺失了 請問是特意移除的嬤
> 
> To fix this, delete `Spine` folder then download spine-unity 3.8 (https://esotericsoftware.com/files/runtimes/unity/spine-unity-3.8-2021-11-10.unitypackage) and import it again.
> 
> Why 3.8? Cause when I try to use the latest version, there will be a `NullReferenceException` if there are operations related to the Skeleton which doesn't know where it's coming from even if you debug it. Also the Spine 2D asset/Spr/Live 2D that @Tualin14 provided is produced in Spine Editor v3.8.76.
> 
> It's a compatibility issue (https://github.com/EsotericSoftware/spine-runtimes/tree/4.1/spine-unity#spine-version)
> 
> > spine-unity works with data exported from Spine 4.1.xx.
> 
> So, if the source is based on v3.8.x, you also need spine-unity 3.8 and so on.
> 
> Hope this help :)
> 
> Edit:
> 
> > 感謝大佬!因為也想做個編輯器 想參考大老的做法
> 
> Oh, looks like you fixed this.

Thanks for your help too ^^

**Comment by Tualin14** [comment]
源码中不带有 Spine 库
可自行下载 [spine-unity 3.8 for Unity 2017.1-2020.3](http://esotericsoftware.com/spine-unity-download/#spine-unity-unitypackages)，并将 `Spine` 添加到项目中。
