### ISSUE TITLE
部分字体不能选择字重

### ISSUE THREAD

**Issue by IF-chan** [Tualin14/baPlayer#11]
比如**_汉仪正圆（HYZhenYuan）_**有七个字重，35S～95S 对应最常用的纤细体（ExtraLight）、细体（Light）、常规（Regular）、准黑（Medium）、中黑（Semibold）、粗体（Bold）和大黑（Heavy）。我这些都安装了，但在选字体界面只有一个HYZhenYuan，无法选择字重。
![11](https://user-images.githubusercontent.com/98469234/224819752-6bef951f-614b-4c72-9fc2-c5b9875a0d06.png)

**Comment by Tualin14** [comment]
需要以管理员安装字体，并重启电脑

**Comment by IF-chan** [comment]
> 需要以管理员安装字体，并重启电脑

怎么以管理员安装字体，我找不到相关选项

**Comment by Tualin14** [comment]
> > 需要以管理员安装字体，并重启电脑
> 
> 怎么以管理员安装字体，我找不到相关选项

就是鼠标右键，选带个盾的安装，应该是叫为所有用户安装

**Comment by kiraio-moe** [comment]
> 怎么以管理员安装字体，我找不到相关选项

Select the font that you want to install > Right Click > Install for all users.

I also don't know why [Font.GetOSInstalledFontNames](https://docs.unity3d.com/ScriptReference/Font.GetOSInstalledFontNames.html "Visit Unity Scripting API") only returns some fonts variations even though I installed them all as Admin.

The font variations that are not listed are:
- Black
- Black Italic
- Extra Bold
- Extra Bold Italic
- Light
- Light Italic
- Medium
- Medium Italic
- Thin
- Thin Italic

![image](https://user-images.githubusercontent.com/58289710/224897948-7390734d-3cb6-4e4d-9dc5-a79f4c443448.png)

**Comment by IF-chan** [comment]
> > > 需要以管理员安装字体，并重启电脑
> > 
> > 怎么以管理员安装字体，我找不到相关选项
> 
> 就是鼠标右键，选带个盾的安装，应该是叫为所有用户安装

我就是这样安装的，但还是没有其他字重

**Comment by Tualin14** [comment]
> 我就是这样安装的，但还是没有其他字重

这样我目前确实没办法了，因为unity就提供了这么一个获取外部字体的方法
所以目前你只能考虑不去用没找到的字体
如果以后有其他办法会加上

**Comment by Tualin14** [comment]
0.3版之后设置预设字体，不再提供自定义字体功能，见 #15
