### ISSUE TITLE
th命令有时无法正常执行

### ISSUE THREAD

**Issue by IF-chan** [Tualin14/baPlayer#16]
有时执行th命令会跳出这样的错误提示
![QQ截图20230404010255](https://user-images.githubusercontent.com/98469234/229578826-3137fe76-49d8-4ef0-9419-50582ae2e35e.png)
语句是这样的：th 星野 '星野' '对策委员会' '对啊，我的那些后辈们还是没有回我……'（应该没啥问题）
加载部分：
load spr 星野 hoshino_spr
load char 绫 1.5 SNTR_Ayaya [L.png, R.png]
load char 梦 0.6 SNTR_Yume [冬.png]
load char 柯林 2 Schale_Colin [L.png]
load bg 1 BG_TrinityClubRoom_Night.jpg
load bg 2 BG_StudentRoom_Night2.jpg
load end

**Comment by Tualin14** [comment]
这个错误是一般是没有找到nameId，所以看看是不是打错了，能提供报错附近的文本吗？

**Comment by IF-chan** [comment]
> 这个错误是一般是没有找到nameId，所以看看是不是打错了，能提供报错附近的文本吗？

今天再运行的时候就能正常运行了，也不清楚原因
附近的文本：
th 绫 '绫' 'SNTR火车司机' '还是谁都联系不上吗？'
th 星野 '星野' '对策委员会' '对啊，我的那些后辈们还是没有回我……'
绫 hl 1
星野 hl 0.5
t '绫' 'SNTR火车司机' '嗯……你说你是跟她们吃完晚饭回去的时候莫名其妙晕倒了？'

**Comment by kiraio-moe** [comment]
As far I know, the "The given key was not present in the dictionary" error also will be triggered if you spam click to progress the story even if you correctly write the story script. Ah, also it occurs when there's choice buttons then you spam click them.
