### ISSUE TITLE
alias command

### ISSUE THREAD

**Issue by Tualin14** [Tualin14/baPlayer#20]
Repeating the **_txt_**, **character name** and their **group** is tiring.
Example:
```text
txt Hifumi 'Remedial Department' 'Ah, Sensei! You are here!'
txt Hifumi 'Remedial Department' 'Ne, just like what I told Sensei on MomoTalk, I just got new peripheral products.'
```

So, we use **alias** to resolve this issue. Instead of writing like above, we can use **alias** to save a specified text then use it later by simply writing the alias name.

Syntax: `alias alias_name "alias content"`

Example:
```text
alias hifumi_say "txt Hifumi 'Remedial Department'" // save the 'txt' command, character name and their group first

hifumi_say 'Ah, Sensei! You are here!' // use them by simply write the alias name
hifumi_say 'Ne, just like what I told Sensei on MomoTalk, I just got new peripheral products.'
```

The output will be the same, but we write it more shortly.

**The important note** in here is that, **you can't use the same alias name that has been given to another command**.
Example:
```txt
// we load the character with the alias name 'hifumi' so we can use it later to do other things like...
// changing the character state and emotion.
load spr hifumi hifumi_spr

// we define an alias with the name 'hifumi' (same as above) to store the txt.
alias hifumi "txt Hifumi 'Remedial Department'"

// in here, the problem will occur. Aris Studio didn't know whether you want to change the behavior...
// of the character or just print the text in the dialogue and the content is 'show'.
hifumi show
hifumi emo Action
hifumi state  03

hifumi 'Ah, Sensei! You are here!'
```

**Comment by kiraio-moe** [comment]
Trying to figure out, why using _alias_ causing the story to continue run (except when selecting button) without showing the dialogue. Using the normal way is fine.

https://github.com/Tualin14/ArisStudio/assets/58289710/c95f5ff2-fd02-4143-8e1f-2cc7cef59405

**Comment by kiraio-moe** [comment]
Fixed! Instead of adding this line to [PreLoad(string[] texts)](https://github.com/Tualin14/ArisStudio/commit/40442e178db4bab328af6ddd0b71a93bdb86e9ad#diff-63fdb2ea83a81792706e788fe15067ad8e1ead0fef002eb83fee83e6159dcd0dR183):
```cs
foreach (var kv in aliasList.Where(kv => text.Contains(kv.Key)))
{
    text = text.Replace(kv.Key, kv.Value);
}
```
place it in [SolveCommand(string text)](https://github.com/Tualin14/ArisStudio/commit/40442e178db4bab328af6ddd0b71a93bdb86e9ad#diff-63fdb2ea83a81792706e788fe15067ad8e1ead0fef002eb83fee83e6159dcd0dR227):
```cs
...

if (nameIdList.ContainsKey(command[0]))
    textCommand = $"{nameIdList[command[0]]} {textCommand}";

foreach (KeyValuePair<string, string> alias in aliasList.Where(alias => textCommand.Contains(alias.Key)))
{
    // if current command contain alias name, replace the command with the alias value.
    textCommand = textCommand.Replace(alias.Key, alias.Value);
}

command = AsCommand.Parse(textCommand);

...
```

**Comment by Tualin14** [comment]
#26

**Comment by Tualin14** [comment]
Archive this repository
