### ISSUE TITLE
标题无法消除

### ISSUE THREAD

**Issue by JY9087** [Tualin14/baPlayer#28]
![屏幕截图 2023-06-11 215206](https://github.com/Tualin14/ArisStudio/assets/57891705/e2d14d3f-085a-4a89-ab55-f7142c5cab8f)

标题一直在最前面，无法消除。其他正常，可以点击以推进剧情

**Comment by kiraio-moe** [comment]
Thanks for reporting, we will look for it.

**Comment by Tualin14** [comment]
> 标题一直在最前面，无法消除。其他正常，可以点击以推进剧情

你用的哪个版本？先不要用0.3预发行版，用0.2(在release叫2.2)。

0.3版本目前是未完成状态，banner这里我也在改运行逻辑，最近有事，下周天才会继续弄。

**Comment by Tualin14** [comment]
Archive this repository
