### ISSUE TITLE
输出Unicode非第0平面字符时软件直接闪退问题

### ISSUE THREAD

**Issue by Fitzgerald-Porthmouth-Koenigsegg** [Tualin14/baPlayer#33]
# 描述

该Bug所呈现为在输出Unicode非第0平面字符时会导致软件直接闪退，无法执行之后的操作。例：
> t \`优香\` \`研讨会\` \`爱丽丝？！你醒了？你还好吗？\`
> t \`爱丽丝\` \`游戏开发部\` \`空固役之呀，些皮耒本𪜀㦖尋老師，結果皮買𠓨文房，㐌固𠊛抌些𢮭昏迷。\`

在调试的过程中，输出文本到最后一句，也就是`空固役之呀，些皮耒本𪜀㦖尋老師，結果皮買𠓨文房，㐌固𠊛抌些𢮭昏迷。`的`𪜀`字的时候，软件直接闪退，在这之后的操作全都无法继续执行。

`𪜀`所在的码位为`U+2A700`。

# 问题出现的频率

100%，必定触发。

# 使用版本 

0.2.25。

# 附加资讯

目前此版本对于字体的支持似乎不友好，默认字体存在fallback（迭返）现象（主要表现为Jhenghei和Yahei互相fallback），而且亦不支持多个字体的调用，`text font`也不生效。例：
> text font Noto Sans SC

字体的名字叫做Noto Sans SC，而在debug窗口输出的状态为：
> Font(Command) changed to Noto 

尝试过使用`_（下划线）`代替`˽（空格）`，但不奏效，依然无法正常调用。
***
以上问题对于Aris Studio的正常使用产生了严重的干扰，烦请拨冗修复，致谢。

**Comment by Tualin14** [comment]
第一个问题应该是字体没有此字符导致的，可以尝试换字体。
第二个问题是unity只提供在系统中加载字体方式，没有其它自定义字体方式，unity会找不到有变体的字体，所以无法解决。

另外，建议去使用 [这个工具](https://aadoc.foxxlight.top/)

**Comment by Tualin14** [comment]
Archive this repository
