### ISSUE TITLE
请更新一下vscode插件对新版的适配

### ISSUE THREAD

**Issue by PsionicZephyr** [Tualin14/baPlayer#35]
也就是把2.22之前的引号''更新到之后版本使用的这个引号``

PS：本人不是没用过AA，但综合考量一些因素最终还是觉得AS好用。AS对网页工具Closuretalk导出的json适配很好，直接Ctrl+H替换掉一些内容就可以变成AS能用的脚本，大大降低工作量，这个是AA做不到的。还有就是AS的资源更新起来方便很多，游戏一更新就能马上把资源拆包来用，AA的资源结构太复杂了

**Comment by Tualin14** [comment]
短时间内没空啊，兄弟。

vscode这个你可以自己弄，主要是这个文件，你看一下应该就会改了，然后vscode安装本地插件。
或者你直接找本地插件中的这个文件改。

https://github.com/ArisStudio/ArisStudio_Legacy_VSCode_extension/blob/main/snippets/as.code-snippets
