### ISSUE TITLE
vscode辅助脚本编写插件需要更新

### ISSUE THREAD

**Issue by IF-chan** [Tualin14/baPlayer#36]
因为文本分隔符更新所以脚本编写插件需要更新

注：可以手动打开**C:\Users\IF\.vscode\extensions\dzaaaaaa.baplayer-command-0.2.0\syntaxes\as.tmLanguage.json**
然后把文件中此部分的`'`改为`
![image](https://github.com/ArisStudio/ArisStudio_Legacy/assets/98469234/4d8e33c1-d314-4d45-b468-d6afdadeb5a6)

**Comment by Tualin14** [comment]
如果需要本地改就可以了，有[这个工具](https://github.com/sanmusen214/arisstudio-blockly)就不更这插件了。
