### ISSUE TITLE
出现按钮的情形下存在反常表现

### ISSUE THREAD

**Issue by WintherChan** [Tualin14/baPlayer#8]
观测到在点选按钮之后，总是要求再次点击才可以继续播放。
虽然发现可以通过适时调整自动播放间隔从而在auto时掩盖这个问题，但是这种反常表现是无法彻底避免的吗？

**Comment by Tualin14** [comment]
下个版本我改改
目前这样是防止点太快出现bug
最近有事，20号左右改

**Comment by Tualin14** [comment]
0.3版已修改
