### ISSUE TITLE
[REQUEST] Add English Documentation

### ISSUE THREAD

**Issue by kiraio-moe** [Tualin14/baPlayer#9]
Hi @Tualin14, great job at Aris Studio!

So, I have managed to translate the documentation to English. It will be benefit many Sensei's to know more
how to work with Aris Studio without being confused with a quick rough machine translated documentation.

You can check it out here: https://github.com/kiraio-moe/ArisStudio-wiki
Some of the content is changed to fit my changes at https://github.com/kiraio-moe/ArisStudio, you may want to edit that.

Waiting for your reply. Thanks.

**Comment by Tualin14** [comment]
Thank you for all your work. But I'm busy these days, so it will be a few days before I can take a look at it.

I'll go ahead and put the link to your English version of the document in readme.md.

**Comment by kiraio-moe** [comment]
Your welcome (◡ ω ◡)
No need to rush, take your time.

**Comment by Tualin14** [comment]
I looked at your project today and I noticed that you made a lot of good changes, thank you very much for your contribution.

Can you change it to unity version 2021.3.12f1 (same as jp version) and push it to as2-dev branch?

I have things to do before the 20th and after that I'll get to work on some logic bug fixes.

Do you know how to write a shader?  I can't write a shader right now, and I want the communication state and normal state to be in one shader so it can load the character only once.

**Comment by kiraio-moe** [comment]
> I looked at your project today and I noticed that you made a lot of good changes, thank you very much for your contribution.

Your welcome :)
I enjoy working on other people's projects that I find interesting.

> Can you change it to unity version 2021.3.12f1 (same as jp version) and push it to as2-dev branch?

Well yeah, the biggest problem of Unity. Version mismatch with other devs.
I don't have Unity 2021.3.12f1 at the moment. But it looks like it will be fine if I push now. There may be slight changes in the API.

Do you want to develop Aris Studio in Unity 2021.3.12f1? Well, uhh... I have bad experiences with Unity 2021, so I still stick with Unity 2020 & 2019.
Is upgrading to 2021 really needed?

> Do you know how to write a shader? I can't write a shader right now, and I want the communication state and normal state to be in one shader so it can load the character only once.

Nah, I don't know how to write a Shader. Even though I'm using the Shader Graph package, I don't know where to start.

**Comment by Tualin14** [comment]
> Is upgrading to 2021 really needed?

I googled and did find that 2021.3.12f1 has API changed that are not compatible with previous versions.
The version is not a big deal, so let's use the 2020 version.

**Comment by kiraio-moe** [comment]
> The version is not a big deal, so let's use the 2020 version.

Sorry to trouble you 😅 
Should I PR now?

Edit: I already did it.

**Comment by Tualin14** [comment]
I have a question with the sln file. 

I find u delete it at [there](https://github.com/kiraio-moe/ArisStudio/commit/d719d176ba6a95ae9e8a7211be556dc7df0c5347#diff-c4cb3f62bcc127601cf3160b3ddf670ac1b8ace763a077f08ce514ce58096bd2), and the code can run without it.
But the project will not open as a project file without it.

So sln file is not required?

**Comment by kiraio-moe** [comment]
> So sln file is not required?

From the [.gitignore](https://github.com/github/gitignore/blob/main/Unity.gitignore#L37) template by @github, it's not needed to include that in VCS (except normal C# project).
Unity will automatically generate them (`.sln` & `.csproj`), if not you can always generate it at `Edit > Preferences > External Tools > Regenerate Project Files`.

Btw, I use this tool https://www.toptal.com/developers/gitignore to generate the .gitignore then combine with the template github provided.

**Comment by Tualin14** [comment]
Thank you for your answer, it is much appreciated.

**Comment by kiraio-moe** [comment]
> Thank you for your answer, it is much appreciated.

Your welcome.
I thinks it's good to talk about the development in Discussions, so the topic doesn't spread all over the place.
